# Generated by Django 4.0.3 on 2022-03-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogTracker',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField()),
                ('status', models.CharField(max_length=255, null=True)),
                ('api', models.CharField(help_text='API URL', max_length=1024, null=True)),
                ('method', models.CharField(db_index=True, max_length=20, null=True)),
                ('headers', models.TextField(null=True)),
                ('client_ip_address', models.CharField(max_length=50, null=True)),
                ('client_ip_geolocation', models.TextField(null=True)),
                ('response', models.TextField(null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Response status code')),
                ('execution_time', models.DecimalField(blank=True, decimal_places=5, help_text='Server execution time (Not complete response time.)', max_digits=8)),
                ('user_agent', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'API Log',
                'verbose_name_plural': 'API Logs',
                'db_table': 'django_logs',
            },
        ),
    ]
